### ISSUE TITLE
trying to figure out where mruby functions are called

### ISSUE THREAD

**Issue by Asmod4n** [rhykw/pdns-mrubybackend#1]
Currently looking through the code and cannot find `mrb_funcall` or similar.

C++ is rather unfamiliar for me :/

**Comment by rhykw** [comment]
Ah...

I did not use `mrb_funcall` in _pdns-mrubybackend_ .

mruby functions are called from  [`code_execute`](https://github.com/rhykw/pdns-mrubybackend/blob/e51db60307968703a3bd44fa0a753e102cc5c615/src/mrubybackend.cc#L112) method.

I use the mrb_load_string_cxt instead of  mrb_funcall.

**Comment by Asmod4n** [comment]
Hm, it should be a lot faster if you don't use that function for each request, it can be used to bootstrap something to be called later.

Is there a way to write a pdns backend plugin without using C++?
